language: node_js
node_js:
  - "12"
dist: trusty
sudo: false

branches:
  only:
   - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/xmas/browser
  fqdn: gifts.loggyt.com
  on:
    branch: master